<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="slider.css" rel="stylesheet">
</head>
<body>
<div class="slider-wrapper">
    <div class="slider-container" >
        <div id="slider-main">
        <div class="slide" >
            <img src="pic52.jpg">
            <span style="bottom:100%">همین حالا خرید کنید</span>
        </div>
        <div class="slide" >
            <img src="pic22.jpg">
            <span  style="bottom:100%">طبیعت در خانه</span>
        </div>
        <div class="slide" >
            <img src="pic25.jpg">
            <span  style="bottom:100%">انوع کاکتوس ها</span>
        </div>
    </div>
        </div>
</div>
<script src="slider.js"></script>
</body>
</html>